server:
  port: 8090

spring:
  application:
    name: microservice-product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 
    username:
    password: 
  jpa:
    hibernate:
      ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/